# pylint: disable=invalid-name, no-member
"""add foreignkey

Revision ID: eed2324cd729
Revises: 7cdd3641177c
Create Date: 2020-05-01 12:43:06.652206

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "eed2324cd729"
down_revision = "7cdd3641177c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_articles_url_id_urls"), "urls", ["url_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_articles_url_id_urls"), type_="foreignkey"
        )

    # ### end Alembic commands ###
