# Generated by Django 3.0.5 on 2020-05-01 07:01

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [("article", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="urls",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to="article.Author",
            ),
        )
    ]
