# Generated by Django 2.1 on 2020-05-01 08:01

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [("article", "0002_auto_20200501_0701")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.URLField(default="https://placehold.it/200x200"),
        )
    ]
