name: Deploy website
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: now deploy
        id: now-deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
        run: |
          sudo npm i -g now
          now env pull
          now -t $ZEIT_TOKEN --prod
      - name: sqlite migrate
        id: sqlite-migrate
        run: |
          cd api
          pip install -r requirements.txt
          alembic upgrade head
