name: Deploy website
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: now deploy
        id: now-deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
        run: |
          sudo npm i -g now
          now -t $ZEIT_TOKEN env pull
          now -t $ZEIT_TOKEN
      - name: Sqlite Migrate
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
        run: |
          pip install -r api/requirements.txt && alembic upgrade head
