name: Deploy website
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: now deploy
        id: now-deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
          NOW_ORD_ID: ${{ secrets.NOW_ORG_ID }}
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
        run: |
          npm i -g now
          now -t $ZEIT_TOKEN
      - name: preview-url
        run: |
          echo ${{ steps.now-deployment.outputs.preview-url }}
